export const requests = {
  items: [
    { id: 0, number: '334455', description: 'Повреждение АОП', address: 'ул. Мира 245, кв. 10', employee: 'Иванов', note: '', authorID: 1 },
    { id: 1, number: '334456', description: 'Нет доступа в интернет', address: 'ул. Ленина 12, кв. 5', employee: 'Петров', note: 'Клиент просит срочно', authorID: 2 },
    { id: 2, number: '334457', description: 'Проблемы с маршрутизацией', address: 'ул. Советская 18, кв. 3', employee: 'Сидоров', note: '', authorID: 3 },
    { id: 3, number: '334458', description: 'Неисправность роутера', address: 'ул. Пушкина 47, кв. 7', employee: 'Кузнецов', note: '', authorID: 4 },
    { id: 4, number: '334459', description: 'Проблемы с кабелем', address: 'ул. Гагарина 21, кв. 12', employee: 'Новиков', note: '', authorID: 1 },
    { id: 5, number: '334460', description: 'Низкая скорость соединения', address: 'ул. Лермонтова 32, кв. 9', employee: 'Федоров', note: 'Проверить оборудование', authorID: 2 },
    { id: 6, number: '334461', description: 'Обрыв линии', address: 'ул. Чехова 5, кв. 14', employee: 'Морозов', note: '', authorID: 3 },
    { id: 7, number: '334462', description: 'Неисправность модема', address: 'ул. Толстого 26, кв. 8', employee: 'Волков', note: '', authorID: 4 },
    { id: 8, number: '334463', description: 'Подключение новых абонентов', address: 'ул. Достоевского 15, кв. 2', employee: 'Зайцев', note: '', authorID: 1 },
    { id: 9, number: '334464', description: 'Необходима настройка Wi-Fi', address: 'ул. Горького 9, кв. 6', employee: 'Иванов', note: '', authorID: 2 },
    { id: 10, number: '334465', description: 'Отсутствие сигнала', address: 'ул. Ленина 34, кв. 4', employee: 'Петров', note: 'Переподключить кабель', authorID: 3 },
    { id: 11, number: '334466', description: 'Неисправность оборудования', address: 'ул. Свердлова 7, кв. 11', employee: 'Сидоров', note: '', authorID: 4 },
    { id: 12, number: '334467', description: 'Проблемы с авторизацией', address: 'ул. Крылова 19, кв. 3', employee: 'Кузнецов', note: '', authorID: 1 },
    { id: 13, number: '334468', description: 'Подключение к сети', address: 'ул. Бабушкина 45, кв. 5', employee: 'Новиков', note: '', authorID: 2 },
    { id: 14, number: '334469', description: 'Настройка IP', address: 'ул. Королева 30, кв. 8', employee: 'Федоров', note: '', authorID: 3 },
    { id: 15, number: '334470', description: 'Проблемы с DNS', address: 'ул. Павлова 6, кв. 2', employee: 'Морозов', note: '', authorID: 4 },
    { id: 16, number: '334471', description: 'Сбой соединения', address: 'ул. Рубинштейна 23, кв. 10', employee: 'Волков', note: '', authorID: 1 },
    { id: 17, number: '334472', description: 'Необходимость замены оборудования', address: 'ул. Жукова 12, кв. 13', employee: 'Зайцев', note: 'Уточнить у клиента', authorID: 2 },
    { id: 18, number: '334473', description: 'Подключение нового оборудования', address: 'ул. Пушкина 2, кв. 6', employee: 'Иванов', note: '', authorID: 3 },
    { id: 19, number: '334474', description: 'Проверка подключения', address: 'ул. Лермонтова 37, кв. 1', employee: 'Петров', note: '', authorID: 4 },
    { id: 20, number: '334475', description: 'Настройка роутера', address: 'ул. Толстого 14, кв. 3', employee: 'Сидоров', note: '', authorID: 1 },
    { id: 21, number: '334476', description: 'Обновление прошивки', address: 'ул. Чехова 22, кв. 4', employee: 'Кузнецов', note: '', authorID: 2 },
    { id: 22, number: '334477', description: 'Перенастройка сети', address: 'ул. Горького 13, кв. 11', employee: 'Новиков', note: '', authorID: 3 },
    { id: 23, number: '334478', description: 'Проблемы с кабельным подключением', address: 'ул. Ленина 56, кв. 8', employee: 'Федоров', note: '', authorID: 4 },
    { id: 24, number: '334479', description: 'Нет соединения с сервером', address: 'ул. Достоевского 19, кв. 5', employee: 'Морозов', note: '', authorID: 1 },
    { id: 25, number: '334480', description: 'Проблемы с подключением Wi-Fi', address: 'ул. Королева 9, кв. 7', employee: 'Волков', note: '', authorID: 2 },
    { id: 26, number: '334481', description: 'Настройка безопасности сети', address: 'ул. Павлова 18, кв. 4', employee: 'Зайцев', note: '', authorID: 3 },
    { id: 27, number: '334482', description: 'Повторное подключение', address: 'ул. Рубинштейна 25, кв. 2', employee: 'Иванов', note: '', authorID: 4 },
    { id: 28, number: '334483', description: 'Установка нового оборудования', address: 'ул. Жукова 11, кв. 9', employee: 'Петров', note: '', authorID: 1 },
    { id: 29, number: '334484', description: 'Перенастройка роутера', address: 'ул. Ленина 3, кв. 10', employee: 'Сидоров', note: '', authorID: 2 },
  ]
}
